apiVersion: v1
kind: Service
metadata:
  name: wp-elb-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <put-your-arn:aws:acm:here>

spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
  loadBalancerSourceRanges:
  - "89.201.163.42/32"
  - "89.101.59.254/30"
  - "95.179.206.218/32"
  selector:
    app: wp-test
